# Generated by Django 4.0.5 on 2022-06-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_members_gruppe_delete_gruppe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='gruppe',
            field=models.ManyToManyField(blank=True, related_name='items', to='members.gruppe'),
        ),
    ]
