# Generated by Django 4.0.5 on 2022-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_gruppe_members_gruppe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='gruppe',
        ),
        migrations.AddField(
            model_name='members',
            name='gruppe',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gruppe',
        ),
    ]
