# Generated by Django 4.0.5 on 2022-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_members_gruppe_members_gruppe_delete_gruppe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='gruppe',
            field=models.TextField(blank=True),
        ),
    ]
