# Generated by Django 4.0.5 on 2022-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='fredag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='mandag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='onsdag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='tirsdag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='torsdag',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
